INSERT INTO news_paper (id,name,country_name,language_id) VALUES (17,'New Age','Bangladesh',3);
INSERT INTO news_paper (id,name,country_name,language_id) VALUES (18,'Daily Sun','Bangladesh',3);
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1087,17,0,'Bangladesh','http://www.newagebd.net/articlelist/302/Bangladesh/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1088,17,0,'World','http://www.newagebd.net/articlelist/295/World/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1089,17,0,'Business','http://www.newagebd.net/articlelist/293/Business/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1090,17,0,'Sport','http://www.newagebd.net/articlelist/291/Sports/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1091,17,0,'Entertainment','http://www.newagebd.net/articlelist/297/Entertainment/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1092,17,0,'Op-Ed','http://www.newagebd.net/articlelist/298/Opinion/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1094,17,0,'Tech','http://www.newagebd.net/articlelist/294/Tech/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1095,17,0,'Health','http://www.newagebd.net/articlelist/378/Health/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1096,17,0,'Science','http://www.newagebd.net/articlelist/382/Science/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1097,17,0,'Offbeat','http://www.newagebd.net/articlelist/296/Offbeat/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1098,17,0,'Youth','http://www.newagebd.net/articlelist/326/Youth/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1099,17,0,'Cartoon','http://www.newagebd.net/articlelist/323/Cartoon/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1100,17,1087,'Country','http://www.newagebd.net/articlelist/305/Country/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1101,17,1087,'Politics','http://www.newagebd.net/articlelist/304/Politics/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1102,17,1087,'Foreign Affairs','http://www.newagebd.net/articlelist/307/Foreign-affairs/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1103,17,1087,'Diaspora','http://www.newagebd.net/articlelist/308/Diaspora/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1105,17,1087,'Housing crisis in focus','http://www.newagebd.net/articlelist/430/Housing-crisis-in-focus/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1106,17,1088,'Asia','http://www.newagebd.net/articlelist/340/Asia/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1107,17,1088,'South Asia','http://www.newagebd.net/articlelist/341/South-Asia/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1108,17,1088,'Middle East','http://www.newagebd.net/articlelist/342/Middle-East/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1109,17,1088,'North America','http://www.newagebd.net/articlelist/392/North-America/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1110,17,1088,'Latin America','http://www.newagebd.net/articlelist/345/Latin-America/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1111,17,1088,'Europe','http://www.newagebd.net/articlelist/343/Europe/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1112,17,1088,'Africa','http://www.newagebd.net/articlelist/347/Africa/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1113,17,1088,'Oceania','http://www.newagebd.net/articlelist/348/Oceania/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1104,17,1089,'Tax','http://www.newagebd.net/articlelist/311/Tax/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1114,17,1089,'Banking','http://www.newagebd.net/articlelist/310/Banking/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1115,17,1089,'Stocks','http://www.newagebd.net/articlelist/309/Stocks/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1116,17,1089,'Apparel','http://www.newagebd.net/articlelist/312/Apparel/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1117,17,1089,'Telecom','http://www.newagebd.net/articlelist/313/Telecom/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1118,17,1089,'Trade & Commerce','http://www.newagebd.net/articlelist/389/Trade-Commerce/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1119,17,1089,'Power & Energy','http://www.newagebd.net/articlelist/390/Power-Energy/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1120,17,1089,'Commodities','http://www.newagebd.net/articlelist/391/Commodities/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1121,17,1089,'Miscellany','http://www.newagebd.net/articlelist/322/Miscellany/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1122,17,1090,'Cricket','http://www.newagebd.net/articlelist/328/Cricket/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1123,17,1090,'Football','http://www.newagebd.net/articlelist/292/Football/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1124,17,1090,'Tennis','http://www.newagebd.net/articlelist/301/Tennis/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1125,17,1090,'Golf','http://www.newagebd.net/articlelist/329/Golf/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1126,17,1090,'Chess','http://www.newagebd.net/articlelist/330/Chess/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1127,17,1090,'Miscellany','http://www.newagebd.net/articlelist/331/Miscellany/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1128,17,1090,'FIFA World Cup','http://www.newagebd.net/articlelist/404/FIFA-World-Cup/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1129,17,1091,'Film','http://www.newagebd.net/articlelist/332/Film/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1130,17,1091,'TV','http://www.newagebd.net/articlelist/333/TV/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1131,17,1091,'Theatre','http://www.newagebd.net/articlelist/335/Theatre/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1132,17,1091,'Music','http://www.newagebd.net/articlelist/336/Music/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1133,17,1091,'Literature','http://www.newagebd.net/articlelist/337/Literature/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1134,17,1091,'Exhibition','http://www.newagebd.net/articlelist/338/Exhibition/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1135,17,1091,'Miscellany','http://www.newagebd.net/articlelist/339/Miscellany/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1136,17,1092,'Editorial','http://www.newagebd.net/articlelist/361/Editorial/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1137,17,1092,'Opinion','http://www.newagebd.net/articlelist/362/Opinion/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1138,18,0,'National','http://www.daily-sun.com/online/national/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1139,18,0,'Economy','http://www.daily-sun.com/online/economy/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1140,18,0,'World','http://www.daily-sun.com/online/world/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1141,18,0,'Sports','http://www.daily-sun.com/online/sports/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1142,18,0,'Entertainment','http://www.daily-sun.com/online/entertainment/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1143,18,0,'Life-Style','http://www.daily-sun.com/online/life-style/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1144,18,0,'Arts','http://www.daily-sun.com/online/arts/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1145,18,0,'Nature','http://www.daily-sun.com/online/nature/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1146,18,0,'Corporate','http://www.daily-sun.com/online/corporate/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1147,18,0,'Opinion','http://www.daily-sun.com/online/opinion/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1148,18,0,'Feature','http://www.daily-sun.com/online/feature/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1149,18,0,'Crime','http://www.daily-sun.com/online/crime/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1150,18,0,'Advice','http://www.daily-sun.com/online/advice/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1151,18,1138,'Politics','http://www.daily-sun.com/online/politics/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1152,18,1138,'Judiciary','http://www.daily-sun.com/online/judiciary/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1153,18,1138,'Campus','http://www.daily-sun.com/online/education-online/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1154,18,1138,'City','http://www.daily-sun.com/online/city/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1155,18,1138,'Districts','http://www.daily-sun.com/online/district-news/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1156,18,1139,'Business','http://www.daily-sun.com/online/business/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1157,18,1143,'Health','http://www.daily-sun.com/online/health/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1158,18,1143,'Travel','http://www.daily-sun.com/online/Travel/page_num','page_num');
INSERT INTO feature (id,news_paper_id,parent_feature_id,title,link_format,link_variable_part_format) VALUES (1159,18,1143,'Sci-Tech','http://www.daily-sun.com/online/sci-tech/page_num','page_num');
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/national/?pg=page_num' WHERE id = 366;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/bd-politics/?pg=page_num' WHERE id = 367;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/whole-country/?pg=page_num' WHERE id = 368;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/world-news/?pg=page_num' WHERE id = 369;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/sports/?pg=page_num' WHERE id = 370;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/entertainment/?pg=page_num' WHERE id = 371;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/economy/?pg=page_num' WHERE id = 372;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/science-and-technology/?pg=page_num' WHERE id = 373;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/culture/?pg=page_num' WHERE id = 374;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/aboard/?pg=page_num' WHERE id = 375;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/capital/?pg=page_num' WHERE id = 376;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/education/?pg=page_num' WHERE id = 377;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/court/?pg=page_num' WHERE id = 378;
UPDATE feature SET link_format = 'http://www.ittefaq.com.bd/all-news/life-style/?pg=page_num' WHERE id = 379;